<a href="https://colab.research.google.com/github/denverkim/DataAnalysis/blob/main/2_1_5_Occupation_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the occupation dataset and assign it to a variable called users and use the 'user_id' as index. 데이터셋을 임포트해서 users라는 변수에 저장한후 user_id를 인덱스로 사용하시오.

import pandas as pd
users = pd.read_csv('/content/occupation.txt', sep='|', index_col='user_id')
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [3]:
# Display the first 25 rows. 처음 25줄
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [5]:
# Display the last 10 rows. 마지막 10줄
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [6]:
# What is the number of observations in the dataset? 관측치의 수
users.shape[0]

943

In [7]:
# What is the number of columns in the dataset? 컬럼의 수
users.shape[1]

4

In [8]:
# Print the name of all the columns. 모든 컬럼의 이름
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [9]:
# How is the dataset indexed? 데이터셋은 어떻게 인덱스 되었나요?
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [10]:
# What is the data type of each column? 각 컬럼의 데이터 타입은?
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [11]:
# Print only the occupation column. 직업컬럼만 출력
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [12]:
# Summarize the data frame (descriptive statistics). 기술통계를 이용하여 데이터요약
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [13]:
# Summarize all the columns. 모든 컬럼을 요약
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [14]:
# Summarize only the occupation column. 직업 컬럼만 요약
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [16]:
# What is the mean age of users? 모든 사용자의 나이의 평균
print(users.age.mean())

34.05196182396607

In [18]:
# How many different occupations there are in this dataset? 직업의 종류는?
print(users.occupation.value_counts().count())
users.occupation.nunique()

21

21

In [20]:
# What is the most frequent occupation? 가장 많은 직업은?
users.occupation.value_counts().index[0]

'student'

In [24]:
# What is the age with least occurrence? 가장 적게 나오는 나이는?
users.age.value_counts().tail(5).index

Index([7, 11, 66, 10, 73], dtype='int64', name='age')