<a href="https://colab.research.google.com/github/denverkim/DataAnalysis/blob/main/2_3_1_%EB%B3%91%ED%95%A9_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 다음 파일을 읽고 데이터 병합을 수행 하시오 (https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true).

import pandas as pd

titanic = pd.read_excel('https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

# 데이터 붙이기

In [2]:
# 상위 1000행을 train으로 나머지 행을 test로 저장
train = titanic.iloc[:1000]
test = titanic.iloc[1000:]

In [4]:
# train, test 위아래로 붙이기
pd.concat([train, test]).head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [5]:
# train, test 옆으로 붙이기
pd.concat([train, test], axis=1).head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,...,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 데이터 병합

In [10]:
# name, pclass, sex, age를 df1(상위 1000행)으로 name, survived를 df2(하위 500행)로 저장
df1 = titanic[:1000][['name', 'pclass', 'sex', 'age']]
df2 = titanic[-500:][['name', 'survived']]

In [15]:
# name 으로 inner join
print(pd.merge(df1, df2, on='name').shape)
pd.merge(df1, df2, on='name').head()

(193, 5)

                                      name  pclass     sex   age  survived
0                  Ford, Mr. Edward Watson       3    male  18.0         0
1                   Ford, Mr. William Neal       3    male  16.0         0
2  Ford, Mrs. Edward (Margaret Ann Watson)       3  female  48.0         0
3                         Fox, Mr. Patrick       3    male   NaN         0
4   Franklin, Mr. Charles (Charles Fardon)       3    male   NaN         0

In [16]:
# name 으로 outer join
print(pd.merge(df1, df2, on='name', how='outer').shape)
pd.merge(df1, df2, on='name', how='outer').head()

(1311, 5)

                               name  pclass     sex   age  survived
0               Abbing, Mr. Anthony     3.0    male  42.0       NaN
1     Abbott, Master. Eugene Joseph     3.0    male  13.0       NaN
2       Abbott, Mr. Rossmore Edward     3.0    male  16.0       NaN
3  Abbott, Mrs. Stanton (Rosa Hunt)     3.0  female  35.0       NaN
4       Abelseth, Miss. Karen Marie     3.0  female  16.0       NaN

In [18]:
# name 으로 left join
print(pd.merge(df1, df2, on='name', how='left').shape)
pd.merge(df1, df2, on='name', how='left').head()

(1002, 5)

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1,female,29.0000,NaN
1,"Allison, Master. Hudson Trevor",1,male,0.9167,NaN
2,"Allison, Miss. Helen Loraine",1,female,2.0000,NaN
3,"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,NaN
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,NaN

In [20]:
# name 으로 right join
print(pd.merge(df1, df2, on='name', how='right').shape)
pd.merge(df1, df2, on='name', how='right').head()

(502, 5)

                                      name  pclass     sex   age  survived
0                  Ford, Mr. Edward Watson     3.0    male  18.0         0
1                   Ford, Mr. William Neal     3.0    male  16.0         0
2  Ford, Mrs. Edward (Margaret Ann Watson)     3.0  female  48.0         0
3                         Fox, Mr. Patrick     3.0    male   NaN         0
4   Franklin, Mr. Charles (Charles Fardon)     3.0    male   NaN         0